### ISSUE TITLE
[BUG] script stop unexpectedly when using -all-images option

### ISSUE THREAD

**Issue by dpkshetty** [ocp-power-automation/openshift-install-power#103]
**Describe the bug**
`openshift-install-powervs create -all-images` script stop unexpectedly
I am following the steps mentioned here...
`https://developer.ibm.com/tutorials/install-ocp-on-power-vs/`

Altho' `rhel` and `rhcos` images are present under "boot images" for my PowerVS service, it fails to detect rhcos image.
Hence I tried with `-all-images` but it stop unexpectedly!

**Expected behavior**
It should list me the images for rhel and rhcos to choose

**Console Output**
```
dpkshetty@DESKTOP-L94HV3O:~/ocp_on_psvs/ocp-install-dir$ openshift-install-powervs create
[setup_tools] Verifying the latest packages and tools
[precheck_input] WARN: No variables specified or var.tfvars does not exist.. running variables command
[setup_tools] Verifying the latest packages and tools
[variables] Trying to login with the provided IBMCLOUD_API_KEY...
[question] > Select the Service Instance name to use: (Power Systems Virtual Server-Techline)
?
- You have answered: Power Systems Virtual Server-Techline
Targeting service crn:v1:bluemix:public:power-iaas:us-south:a/a39ac7399e414b87e56898b0c3dcda59:bd64dd0b-7a6e-4ce0-b97b-eb2edc606581::...
[variables] Gathering information from the selected Service Instance... Please wait
[variables] ERROR: Cannot find RHCOS image for OCP 4.6! Please use option '-all-images' if you have already imported the image


dpkshetty@DESKTOP-L94HV3O:~/ocp_on_psvs/ocp-install-dir$ openshift-install-powervs create -all-images
[setup_tools] Verifying the latest packages and tools
[precheck_input] WARN: No variables specified or var.tfvars does not exist.. running variables command
[setup_tools] Verifying the latest packages and tools
[variables] Trying to login with the provided IBMCLOUD_API_KEY...
[question] > Select the Service Instance name to use: (Power Systems Virtual Server-Techline)
?
- You have answered: Power Systems Virtual Server-Techline
Targeting service crn:v1:bluemix:public:power-iaas:us-south:a/a39ac7399e414b87e56898b0c3dcda59:bd64dd0b-7a6e-4ce0-b97b-eb2edc606581::...
[variables] Gathering information from the selected Service Instance... Please wait
dpkshetty@DESKTOP-L94HV3O:~/ocp_on_psvs/ocp-install-dir$

```

**Desktop (please complete the following information):**
 - OS: Win10
 - Version Win10
 - Windows terminal WSL Ubuntu 20.04

**Additional context**

**Comment by dpkshetty** [comment]
![pic-psvs-images](https://user-images.githubusercontent.com/6286819/102994828-d8f61d00-4545-11eb-88a9-c92d5779e01a.JPG)

Attaching the picture of the boot images I have in my PowerVS service.

**Comment by yussufsh** [comment]
@dpkshetty Could you please try running the command with `-trace` option and let me know?

**Comment by dpkshetty** [comment]
@yussufsh found the issue.... 
https://github.com/ocp-power-automation/openshift-install-power/blob/852d3191d4bf39fdc75e6f7b54855afccd542361/openshift-install-powervs#L925
It expects the cos image name of the pattern `rhcos-46-` 
Where has that been documented ? How will the user know that is the expectation ? :) 

And here is the bigger issue.. even if you tell this in the resulting error msg (which currently you don't!) there is no option to rename the image in COS !! .. and 120GB image takes atleast 25-30 mins to import, so we are effectively saying we expect User to reimport with the right name and waste 25-30 mins again! ?

**Comment by dpkshetty** [comment]
I proposed a fix to let Users know as part of pre-req
https://github.com/ocp-power-automation/openshift-install-power/pull/104

**Comment by yussufsh** [comment]
@dpkshetty that is not the problem here.. I guess you do not have a network created in your cloud instance yet.

No need to rename the images... The can be taken care with the `-all-images` option.

**Comment by dpkshetty** [comment]
@yussufsh From the above error I provided..how do you conclude that the network was not created ?
BTW you are right.. network was not created.. but nor was it mentioned in any of the pre-req section of the README :) 
I hope my above pull req #104 still holds :)

**Comment by yussufsh** [comment]
No network in script is fixed by https://github.com/ocp-power-automation/openshift-install-power/pull/105
The document is update for per-req by #104
