### ISSUE TITLE
[FEATURE] Create container image with the script and dependencies

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/openshift-install-power#109]
**Is your feature request related to a problem? Please describe.**
A container image with the script and the dependencies including the terraform code will provide additional flexibility and also enable additional use cases. For example deploying a cluster as part of a CI/CD workflow. 

**Describe the solution you'd like**
A container image having the following
1. installer script
2. dependencies - terraform, ibmcloud, oc binaries
3. TF automation code

**Comment by bpradipt** [comment]
cc @Prajyot-Parab @rpsene @yussufsh

**Comment by rpsene** [comment]
you can copy/paste whatever you want from https://github.com/rpsene/openshift-on-powervs-quick-deploy
the images with the dependencies are already available at https://github.com/ocp-power-automation/powervs-container-host

**Comment by rpsene** [comment]
@Elayaraja-Dhanapal this is a duplication of the work you have been doing.

**Comment by bpradipt** [comment]
@Elayaraja-Dhanapal lets identify how we can reuse your work so that we can get this feature with minimalistic changes

**Comment by yussufsh** [comment]
I have created the Dockerfile for this project at #111. Thanks @rpsene for the pieces.

We can use the same for ppc64le with no changes to the Dockerfile when the install script will support ppc64le in future.

Once we have all the approvals for hosting the Docker images we can write the travis config for multi arch image push.

**Comment by rpsene** [comment]
@yussufsh everything you need is here https://github.com/ocp-power-automation/powervs-container-host/blob/main/.travis.yml and the images located at https://quay.io/repository/powercloud/powervs-container-host. 

No legal approval should be required given that all source code is already public available.

**Comment by aishwaryabk** [comment]
I have modified the existing Dockerfile and raised a new PR #133.

**Comment by yussufsh** [comment]
Lets divide the issue into 3 part solution:
1. Create a dockerfile with the script as entrypoint PR #133 
2. Travis config for creating and publishing multi arch images (TODO)
3. Doc update on how to use the docker image (TODO)

**Comment by bpradipt** [comment]
https://github.com/ocp-power-automation/openshift-install-power/pull/174

**Comment by yussufsh** [comment]
Docker images are being published at https://quay.io/repository/powercloud/openshift-install-powervs using prow jobs.
