### ISSUE TITLE
[BUG] Accessing cluster using local `oc` doesn't work as documented

### ISSUE THREAD

**Issue by dpkshetty** [ocp-power-automation/openshift-install-power#112]
**Describe the bug**
After succesfull completion of the `openshift-install-powervs create` script, we get the final msg, part of which says...
`To access the cluster on local system when using 'oc' run: export KUBECONFIG=/home/dpkshetty/ocp_on_psvs/ocp-install-dir/automation/kubeconfig`
But that didn't work for me!

**To Reproduce**
```
dpkshetty@DESKTOP-L94HV3O:~$ export KUBECONFIG=/home/dpkshetty/ocp_on_psvs/ocp-install-dir/automation/kubeconfig
dpkshetty@DESKTOP-L94HV3O:~$ less $KUBECONFIG
dpkshetty@DESKTOP-L94HV3O:~$ oc get nodes
The connection to the server api.deepakcs-ocp-psvs-637a.ocp.deepakcs:6443 was refused - did you specify the right host or port?
dpkshetty@DESKTOP-L94HV3O:~$ ping api.deepakcs-ocp-psvs-637a.ocp.deepakcs
PING api.deepakcs-ocp-psvs-637a.ocp.deepakcs (52.117.41.83) 56(84) bytes of data.
64 bytes from api.deepakcs-ocp-psvs-637a.ocp.deepakcs (52.117.41.83): icmp_seq=1 ttl=48 time=285 ms
64 bytes from api.deepakcs-ocp-psvs-637a.ocp.deepakcs (52.117.41.83): icmp_seq=2 ttl=48 time=303 ms
^C
--- api.deepakcs-ocp-psvs-637a.ocp.deepakcs ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 284.732/294.057/303.382/9.325 ms
dpkshetty@DESKTOP-L94HV3O:~$
```

**Expected behavior**
`oc` from my local terminal should work as documented

**Console Output**
See above

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04
 - Windows terminal: WSL

**Additional context**
None

**Comment by dpkshetty** [comment]
Additionally, people coming to OCP on PowerVS from OCP on IBM Cloud experience, would expect the `oc` login to work using the GUI/console oauth/token method. I am referring to the below steps....
* Click on `kube:admin` on the top right
*  Select "Copy login command"
* Copy the `oc` login cli shown in the resulting oauth page

The above too didn't work for me.
In general for any OCP cluster, the above method should work and is expected to work

**Comment by bpradipt** [comment]
@dpkshetty which DC this cluster is running? Please check this - https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-network-security

**Comment by dpkshetty** [comment]
@bpradipt thanks for the link... I see this in there...
`The port 6443 is also open for miscellaneous purposes. This port will not be open for the WDC04 and DAL13 data centers.`

Unfortunatly my PowerVS service is running in Dallas.
So looks like then there is no way unless opting for DirectLink connect.. which needs additional charges

Maybe then we should mention the above somewhere and/or have a quick reference troubleshooting section in the README for readers to get enlightened on the above ?

**Comment by bpradipt** [comment]
Yes, good suggestion. We can clearly mention in the o/p that CLI login (6443) will not work for WDC04 and DAL13 DC.

**Comment by dpkshetty** [comment]
> Yes, good suggestion. We can clearly mention in the o/p that CLI login (6443) will not work for WDC04 and DAL13 DC.

+ for more details, refer to the network link you had provided above
