### ISSUE TITLE
The output is adding some extra text

### ISSUE THREAD

**Issue by Shilpi-Das1** [ocp-power-automation/openshift-install-power#142]
Running this command printing some extra text ./openshift-install-powervs output bastion_public_ip

**To Reproduce**
1)Deploy cluster using script
2) Run command ./openshift-install-powervs output bastion_public_ip

**Expected behavior**
It should print only the IP address
192.168.xx.xx

**Actual behavior**
Its printing
[0;36m[setup_tools] Verifying the latest packages and tools
192.168.xx.xx
**Console Output**
```
./openshift-install-powervs output bastion_public_ip

[0;36m[setup_tools] Verifying the latest packages and tools
192.168.xx.xx
```

**Desktop (please complete the following information):**
 - OS: Ubuntu x86

**Additional context**
The same thing is happening with other output variables

**Comment by yussufsh** [comment]
Thanks @Shilpi-Das1 for reporting the issue. Will work on fixing this.

**Comment by yussufsh** [comment]
Re-opening this as the merged changes are not good and needs to be reverted.
