### ISSUE TITLE
Output Variable printing extra text[BUG]

### ISSUE THREAD

**Issue by Shilpi-Das1** [ocp-power-automation/openshift-install-power#152]
Running this command printing some extra text ./openshift-install-powervs output bastion_public_ip

To Reproduce
1)Deploy cluster using script
2) Run command ./openshift-install-powervs -ignore-os-checks output bastion_public_ip

Expected behavior
It should print only the IP address
169.57.xx.xx

Actual behavior
Its printing
[1;33m[main] WARN: Ignoring operating system related checks 169.57.xx.xx

This bug is similar to https://github.com/ocp-power-automation/openshift-install-power/issues/142

**Comment by yussufsh** [comment]
This is specific to `-ignore-os-checks` or `-trace` options. We can have hard checks for such options to not display any other 'useful' messages. Let us think through it.

Only workaround I suggest is try to read the last line from the output for now :)

**Comment by yussufsh** [comment]
`trace` will always display the commands run, you cannot use it if you need a single line output.

For WARN messages I will be adding a flag to ignore warning messages.
