### ISSUE TITLE
[BUG] Release image not working with Travis config

### ISSUE THREAD

**Issue by yussufsh** [ocp-power-automation/openshift-install-power#162]
**Describe the bug**
There is no trigger on Travis build for building and releasing image on tags.

**Additional context**
We now shifted to prow and the configurations there also not working on tags.

**Comment by yussufsh** [comment]
@Prajyot-Parab could you please follow up on this. The prow job should be triggered when a new release is created.

**Comment by mkumatag** [comment]
> @Prajyot-Parab could you please follow up on this. The prow job should be triggered when a new release is created.

I see webhook itself is not configured for this repository, lemme do that to act on the events.

**Comment by mkumatag** [comment]
Its configured now, lets see if you can create something to see if it is really working or not?!

**Comment by yussufsh** [comment]
Let me create a new tag now.

**Comment by yussufsh** [comment]
@mkumatag I don't think its working with new (tag)[https://github.com/ocp-power-automation/openshift-install-power/releases/tag/v1.2.2]

Could be configuration issues. Trigger on new tags is somewhat complex for PROW.

**Comment by mkumatag** [comment]
> @mkumatag I don't think its working with new [tag](https://github.com/ocp-power-automation/openshift-install-power/releases/tag/v1.2.2)
> 
> Could be configuration issues. Trigger on new tags is somewhat complex for PROW.

You are right... Have seen some discussions around the same..

**Comment by aishwaryabk** [comment]
@yussufsh 
The Travis job is working for me.
build on a new release - https://travis-ci.com/github/aishwaryabk/openshift-install-power/builds/224746209
build on commit - https://travis-ci.com/github/aishwaryabk/openshift-install-power/jobs/511999993

**Comment by Prajyot-Parab** [comment]
Release Images are being pushed via Prow config.

**Comment by mkumatag** [comment]
> Release Images are being pushed via Prow config.

Are you sure about this? because we have seen issues while building/pushing them via prow!

**Comment by yussufsh** [comment]
@mkumatag yes it worked when @bpradipt created a new release with some magic.
