### ISSUE TITLE
[FEATURE] Allow attaching mixed storage

### ISSUE THREAD

**Issue by manojnkumar** [ocp-power-automation/openshift-install-power#183]
**Is your feature request related to a problem? Please describe.**
Currently if you deploy a cluster on PowerVS, if the boot volume and extra volume fall on different tiers of storage, the deployment fails with: 
```
Error: failed to provision Failed to Create PVM Instance :[POST /pcloud/v1/cloud-instances/{cloud_instance_id}/pvm-instances][400] pcloudPvminstancesPostBadRequest &{Code:0 Description:bad request: calculated parameter has failed for cloud-instance 3808f2f383f04938a5aeae88e027014c: validate volumes failed, all volumes are not in the same VM deployment storage pool Tier3-IOPS-1 Error:bad request Message:}
on modules/1_prepare/prepare.tf line 77, in resource "ibm_pi_instance" "bastion":
 77: resource "ibm_pi_instance" "bastion" {
 ```

**Describe the solution you'd like**
The PowerVS instances now support mixing storage tiers. Details are provided here: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-power-iaas-faqs#mixed_storage

To accomplish this you must modify the PVM instance and set the new PVM instance storagePoolAffinity property to false. 

**Describe alternatives you've considered**
Always use the same tier for storage.

**Additional context**
![image (2)](https://user-images.githubusercontent.com/11194916/138111854-77bb2ef4-1223-4ca6-ba51-c4ff90d8ad61.png)

**Comment by yussufsh** [comment]
We original issues fixed by allowing use of the image storage pool for volumes and instances.
