### ISSUE TITLE
Allow setting vpc region while generating the variables

### ISSUE THREAD

**Issue by yussufsh** [ocp-power-automation/openshift-install-power#184]
In addition to #164 we need to allow user to set vpc/is region during variables command.

**Comment by yussufsh** [comment]
@aishwaryabk can you please take this up?

**Comment by yussufsh** [comment]
@sajauddin @cs-zhang @Prajyot-Parab

**Comment by aishwaryabk** [comment]
@yussufsh Sure.
Raised PR - https://github.com/ocp-power-automation/openshift-install-power/pull/185

**Comment by yussufsh** [comment]
This is fixed.
