### ISSUE TITLE
[BUG] Reboot functionality not working when script fails once

### ISSUE THREAD

**Issue by Shilpi-Das1** [ocp-power-automation/openshift-install-power#202]
OS_TYPE x86 ubuntu 20.04

OCP deployment details
CoreOS version 4.12

[logs (1).tar.gz](https://github.com/ocp-power-automation/openshift-install-power/files/9444284/logs.1.tar.gz)
[trace_logs.txt](https://github.com/ocp-power-automation/openshift-install-power/files/9444290/trace_logs.txt)

**Comment by yussufsh** [comment]
Even with the fix https://github.com/ocp-power-automation/openshift-install-power/issues/200 noticed that the nodes are not rebooting.
After debugging found that the instance names including the bastion are having the zone name added to it by default. This leads to generation of wrong host/node name where the monitor and reboot code is unable to identify the given instance.

**Comment by yussufsh** [comment]
I have created https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/439 which adds an output `name_prefix` can be used to derive the instance name instead of using the `cluster_id`.
