### ISSUE TITLE
Encountering volume not found message in Destroy operation

### ISSUE THREAD

**Issue by kabhiibm** [ocp-power-automation/openshift-install-power#208]
**Describe the bug**
While destroying an OCP cluster on PowerVS, the cluster is destroyed on the ibmcloud but we have started observing an error message.

**To Reproduce**
Command to reproduce the behavior: **./openshift-install-powervs destroy -ignore-os-checks -force-destroy**

**Expected behavior**

**Console Output**

```
Attempt: 1/5
[retry_terraform] Encountered below errors:
│ Error: failed to perform the Get Volume Operation for volume f22a5a94-8680-4ece-8cfb-9190b5268c10 with error [GET /pcloud/v1/cloud-instances/{cloud_instance_id}/volumes/{volume_id}][404] pcloudCloudinstancesVolumesGetNotFound  &{Code:0 Description:volume does not exist, id: f22a5a94-8680-4ece-8cfb-9190b5268c10 Error:volume not found Message:}
[retry_terraform] WARN: Issues were seen while running the terraform command. Attempting to run again...
```

**Comment by yussufsh** [comment]
This is ibmcloud provider issue, it should remove state of volume if 404. Even before they were not having 404 defined in swagger, I will raise an issue with the provider soon.

As a workaround do this...
```
cd automation
../terraform state rm 'module.prepare.ibm_pi_volume.volume[0]'
cd ..
./openshift-install-powervs destroy
```

**Comment by yussufsh** [comment]
Workaround provided.
