### ISSUE TITLE
[FEATURE] Able to run multiple deployments on a client machine using different install dir

### ISSUE THREAD

**Issue by yussufsh** [ocp-power-automation/openshift-install-power#52]
**Is your feature request related to a problem? Please describe.**
The script is not able to on multiple install directory in parallel. I am not able to do two deploys at a time.

**Describe the solution you'd like**
I should be able to do more than 1 deployment using different install/config directory.

**Describe alternatives you've considered**
The problem is the ibmcloud CLI config is placed in HOME directory of current user. We can change that using environment variable `IBMCLOUD_HOME=<install-dir>`.

**Additional context**
The ibmcloud CLI config stores the current target CRN in `~/.bluemix/plugins/power-iaas/config.json` making it diffult to run more than one deployment on different regions or service instances.

**Comment by rpsene** [comment]
you can reuse the same approach used at https://github.com/rpsene/openshift-on-powervs-quick-deploy
